/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExportData {
  'records' : Array<HabitRecord>,
  'habits' : Array<Habit>,
  'profile' : [] | [UserProfile],
}
export interface Habit {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'unit' : HabitUnit,
  'weeklyTarget' : bigint,
}
export interface HabitRecord {
  'day' : bigint,
  'completedAt' : [] | [Time],
  'month' : bigint,
  'habitName' : string,
  'year' : bigint,
  'habitId' : string,
  'amount' : [] | [bigint],
}
export type HabitUnit = { 'custom' : string } |
  { 'reps' : null } |
  { 'time' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHabit' : ActorMethod<[string, bigint, HabitUnit], string>,
  'deleteHabit' : ActorMethod<[string], undefined>,
  'exportAllData' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    ExportData
  >,
  'exportSelectedHabitsData' : ActorMethod<
    [Array<string>, bigint, bigint, bigint, bigint, bigint, bigint],
    ExportData
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getMonthlyRecords' : ActorMethod<[bigint, bigint], Array<HabitRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleHabitCompletion' : ActorMethod<
    [string, bigint, bigint, bigint, [] | [bigint]],
    undefined
  >,
  'updateHabitUnit' : ActorMethod<[string, HabitUnit], undefined>,
  'updateHabitWeeklyTarget' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];