/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DefaultAmount = [] | [bigint];
export interface DiagnosticLog { 'message' : string, 'timestamp' : Time }
export interface DiaryEntry {
  'id' : bigint,
  'asset' : string,
  'date' : bigint,
  'notes' : string,
  'amount' : bigint,
}
export interface ExportData {
  'records' : Array<HabitRecord>,
  'monthlyTargets' : Array<MonthlyTarget>,
  'habits' : Array<Habit>,
  'profile' : [] | [UserProfile],
}
export interface Habit {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'unit' : HabitUnit,
  'defaultAmount' : DefaultAmount,
  'weeklyTarget' : bigint,
}
export interface HabitRecord {
  'day' : bigint,
  'completedAt' : [] | [Time],
  'month' : bigint,
  'habitName' : string,
  'unit' : HabitUnit,
  'year' : bigint,
  'habitId' : string,
  'amount' : [] | [bigint],
}
export type HabitUnit = { 'custom' : string } |
  { 'none' : null } |
  { 'reps' : null } |
  { 'time' : null };
export interface MonthlyTarget {
  'month' : bigint,
  'year' : bigint,
  'habitId' : string,
  'amount' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDiaryEntry' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'addInvestmentGoal' : ActorMethod<[string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHabit' : ActorMethod<
    [string, bigint, HabitUnit, DefaultAmount],
    string
  >,
  'deleteHabit' : ActorMethod<[string], undefined>,
  'exportAllData' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    ExportData
  >,
  'exportSelectedHabitsData' : ActorMethod<
    [Array<string>, bigint, bigint, bigint, bigint, bigint, bigint],
    ExportData
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDiaryEntries' : ActorMethod<[], Array<DiaryEntry>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getLifetimeTotal' : ActorMethod<[string], bigint>,
  'getLogs' : ActorMethod<[], Array<DiagnosticLog>>,
  'getMonthlyRecords' : ActorMethod<[bigint, bigint], Array<HabitRecord>>,
  'getMonthlyTarget' : ActorMethod<
    [string, bigint, bigint],
    [] | [MonthlyTarget]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkDiaryEntryToGoal' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'testLog' : ActorMethod<[string], string>,
  'toggleHabitCompletion' : ActorMethod<
    [string, bigint, bigint, bigint, DefaultAmount],
    undefined
  >,
  'updateHabitDefaultAmount' : ActorMethod<[string, DefaultAmount], undefined>,
  'updateHabitName' : ActorMethod<[string, string], undefined>,
  'updateHabitUnit' : ActorMethod<[string, HabitUnit], undefined>,
  'updateHabitWeeklyTarget' : ActorMethod<[string, bigint], undefined>,
  'updateMonthlyTarget' : ActorMethod<
    [string, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];