/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitUnit = IDL.Variant({
  'custom' : IDL.Text,
  'reps' : IDL.Null,
  'time' : IDL.Null,
});
export const Time = IDL.Int;
export const HabitRecord = IDL.Record({
  'day' : IDL.Nat,
  'completedAt' : IDL.Opt(Time),
  'month' : IDL.Nat,
  'habitName' : IDL.Text,
  'year' : IDL.Nat,
  'habitId' : IDL.Text,
  'amount' : IDL.Opt(IDL.Nat),
});
export const Habit = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'unit' : HabitUnit,
  'weeklyTarget' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExportData = IDL.Record({
  'records' : IDL.Vec(HabitRecord),
  'habits' : IDL.Vec(Habit),
  'profile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHabit' : IDL.Func([IDL.Text, IDL.Nat, HabitUnit], [IDL.Text], []),
  'deleteHabit' : IDL.Func([IDL.Text], [], []),
  'exportAllData' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [ExportData],
      ['query'],
    ),
  'exportSelectedHabitsData' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [ExportData],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getMonthlyRecords' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(HabitRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleHabitCompletion' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateHabitUnit' : IDL.Func([IDL.Text, HabitUnit], [], []),
  'updateHabitWeeklyTarget' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitUnit = IDL.Variant({
    'custom' : IDL.Text,
    'reps' : IDL.Null,
    'time' : IDL.Null,
  });
  const Time = IDL.Int;
  const HabitRecord = IDL.Record({
    'day' : IDL.Nat,
    'completedAt' : IDL.Opt(Time),
    'month' : IDL.Nat,
    'habitName' : IDL.Text,
    'year' : IDL.Nat,
    'habitId' : IDL.Text,
    'amount' : IDL.Opt(IDL.Nat),
  });
  const Habit = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'unit' : HabitUnit,
    'weeklyTarget' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExportData = IDL.Record({
    'records' : IDL.Vec(HabitRecord),
    'habits' : IDL.Vec(Habit),
    'profile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHabit' : IDL.Func([IDL.Text, IDL.Nat, HabitUnit], [IDL.Text], []),
    'deleteHabit' : IDL.Func([IDL.Text], [], []),
    'exportAllData' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [ExportData],
        ['query'],
      ),
    'exportSelectedHabitsData' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [ExportData],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getMonthlyRecords' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(HabitRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleHabitCompletion' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateHabitUnit' : IDL.Func([IDL.Text, HabitUnit], [], []),
    'updateHabitWeeklyTarget' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };