/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExportData {
    monthlyTargets: Array<MonthlyTarget>;
    investmentDiaryEntries: Array<InvestmentDiaryEntry>;
    habitRecords: Array<HabitRecord>;
    diaryEntries: Array<[string, DiaryEntry]>;
    investmentGoals: Array<InvestmentGoal>;
    habits: Array<Habit>;
    profile?: UserProfile;
}
export type Time = bigint;
export type HabitUnit = {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "reps";
    reps: null;
} | {
    __kind__: "time";
    time: null;
};
export interface DiaryEntry {
    title: string;
    content: string;
}
export interface MonthlyTarget {
    month: bigint;
    year: bigint;
    habitId: string;
    amount: bigint;
}
export interface UpdateInvestmentGoal {
    target: bigint;
    currentlyHeld: bigint;
}
export interface Habit {
    id: string;
    name: string;
    createdAt: Time;
    unit: HabitUnit;
    defaultAmount: DefaultAmount;
    weeklyTarget: bigint;
}
export type DefaultAmount = bigint | null;
export interface NewInvestmentGoal {
    asset: string;
    target: bigint;
    currentlyHeld: bigint;
}
export interface InvestmentGoal {
    id: bigint;
    asset: string;
    target: bigint;
    currentlyHeld: bigint;
}
export interface HabitRecord {
    day: bigint;
    completedAt?: Time;
    month: bigint;
    habitName: string;
    unit: HabitUnit;
    year: bigint;
    habitId: string;
    amount?: bigint;
}
export interface DiagnosticLog {
    message: string;
    timestamp: Time;
}
export interface InvestmentDiaryEntry {
    id: bigint;
    asset: string;
    date: bigint;
    notes: string;
    amount: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDiaryEntry(date: bigint, asset: string, amount: bigint, notes: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createHabit(name: string, weeklyTarget: bigint, unit: HabitUnit, defaultAmount: DefaultAmount): Promise<string>;
    createInvestmentGoal(newGoal: NewInvestmentGoal): Promise<bigint>;
    deleteHabit(habitId: string): Promise<void>;
    deleteInvestmentGoal(goalId: bigint): Promise<void>;
    exportAllData(startDay: bigint, startMonth: bigint, startYear: bigint, endDay: bigint, endMonth: bigint, endYear: bigint): Promise<ExportData>;
    getAllDiaryEntries(): Promise<Array<[string, DiaryEntry]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDiaryEntries(): Promise<Array<InvestmentDiaryEntry>>;
    getDiaryEntry(date: string): Promise<DiaryEntry | null>;
    getGoalProgress(goalId: bigint): Promise<bigint | null>;
    getHabits(): Promise<Array<Habit>>;
    getInvestmentGoals(): Promise<Array<InvestmentGoal>>;
    getLifetimeTotal(habitId: string): Promise<bigint>;
    getLogs(): Promise<Array<DiagnosticLog>>;
    getMonthlyRecords(month: bigint, year: bigint): Promise<Array<HabitRecord>>;
    getMonthlyTarget(habitId: string, month: bigint, year: bigint): Promise<MonthlyTarget | null>;
    getTotalGoalsProgress(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    healthCheck(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDiaryEntry(date: string, title: string, content: string): Promise<void>;
    testLog(_message: string): Promise<string>;
    toggleHabitCompletion(habitId: string, day: bigint, month: bigint, year: bigint, amount: DefaultAmount): Promise<void>;
    updateHabitDefaultAmount(habitId: string, newDefaultAmount: DefaultAmount): Promise<void>;
    updateHabitName(habitId: string, newName: string): Promise<void>;
    updateHabitUnit(habitId: string, newUnit: HabitUnit): Promise<void>;
    updateHabitWeeklyTarget(habitId: string, newWeeklyTarget: bigint): Promise<void>;
    updateInvestmentGoal(goalId: bigint, updates: UpdateInvestmentGoal): Promise<void>;
    updateMonthlyTarget(habitId: string, amount: bigint, month: bigint, year: bigint): Promise<void>;
}
import type { DefaultAmount as _DefaultAmount, DiaryEntry as _DiaryEntry, ExportData as _ExportData, Habit as _Habit, HabitRecord as _HabitRecord, HabitUnit as _HabitUnit, InvestmentDiaryEntry as _InvestmentDiaryEntry, InvestmentGoal as _InvestmentGoal, MonthlyTarget as _MonthlyTarget, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDiaryEntry(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDiaryEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDiaryEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createHabit(arg0: string, arg1: bigint, arg2: HabitUnit, arg3: DefaultAmount): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0, arg1, to_candid_HabitUnit_n3(this._uploadFile, this._downloadFile, arg2), to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0, arg1, to_candid_HabitUnit_n3(this._uploadFile, this._downloadFile, arg2), to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createInvestmentGoal(arg0: NewInvestmentGoal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvestmentGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvestmentGoal(arg0);
            return result;
        }
    }
    async deleteHabit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteInvestmentGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvestmentGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvestmentGoal(arg0);
            return result;
        }
    }
    async exportAllData(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<ExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAllData(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_ExportData_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAllData(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_ExportData_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDiaryEntries(): Promise<Array<[string, DiaryEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiaryEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiaryEntries();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiaryEntries(): Promise<Array<InvestmentDiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaryEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaryEntries();
            return result;
        }
    }
    async getDiaryEntry(arg0: string): Promise<DiaryEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaryEntry(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaryEntry(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoalProgress(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoalProgress(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoalProgress(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestmentGoals(): Promise<Array<InvestmentGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentGoals();
            return result;
        }
    }
    async getLifetimeTotal(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLifetimeTotal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLifetimeTotal(arg0);
            return result;
        }
    }
    async getLogs(): Promise<Array<DiagnosticLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs();
            return result;
        }
    }
    async getMonthlyRecords(arg0: bigint, arg1: bigint): Promise<Array<HabitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyRecords(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyRecords(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyTarget(arg0: string, arg1: bigint, arg2: bigint): Promise<MonthlyTarget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyTarget(arg0, arg1, arg2);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyTarget(arg0, arg1, arg2);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalGoalsProgress(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalGoalsProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalGoalsProgress();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDiaryEntry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDiaryEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDiaryEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async testLog(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.testLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testLog(arg0);
            return result;
        }
    }
    async toggleHabitCompletion(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: DefaultAmount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHabitCompletion(arg0, arg1, arg2, arg3, to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHabitCompletion(arg0, arg1, arg2, arg3, to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateHabitDefaultAmount(arg0: string, arg1: DefaultAmount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitDefaultAmount(arg0, to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitDefaultAmount(arg0, to_candid_DefaultAmount_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHabitName(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitName(arg0, arg1);
            return result;
        }
    }
    async updateHabitUnit(arg0: string, arg1: HabitUnit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitUnit(arg0, to_candid_HabitUnit_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitUnit(arg0, to_candid_HabitUnit_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHabitWeeklyTarget(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitWeeklyTarget(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitWeeklyTarget(arg0, arg1);
            return result;
        }
    }
    async updateInvestmentGoal(arg0: bigint, arg1: UpdateInvestmentGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvestmentGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvestmentGoal(arg0, arg1);
            return result;
        }
    }
    async updateMonthlyTarget(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyTarget(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyTarget(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_DefaultAmount_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DefaultAmount): DefaultAmount {
    return from_candid_opt_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ExportData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): ExportData {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_HabitRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitRecord): HabitRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HabitUnit_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitUnit): HabitUnit {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Habit_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Habit): Habit {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiaryEntry]): DiaryEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyTarget]): MonthlyTarget | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: bigint;
    completedAt: [] | [_Time];
    month: bigint;
    habitName: string;
    unit: _HabitUnit;
    year: bigint;
    habitId: string;
    amount: [] | [bigint];
}): {
    day: bigint;
    completedAt?: Time;
    month: bigint;
    habitName: string;
    unit: HabitUnit;
    year: bigint;
    habitId: string;
    amount?: bigint;
} {
    return {
        day: value.day,
        completedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.completedAt)),
        month: value.month,
        habitName: value.habitName,
        unit: from_candid_HabitUnit_n13(_uploadFile, _downloadFile, value.unit),
        year: value.year,
        habitId: value.habitId,
        amount: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: _Time;
    unit: _HabitUnit;
    defaultAmount: _DefaultAmount;
    weeklyTarget: bigint;
}): {
    id: string;
    name: string;
    createdAt: Time;
    unit: HabitUnit;
    defaultAmount: DefaultAmount;
    weeklyTarget: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        unit: from_candid_HabitUnit_n13(_uploadFile, _downloadFile, value.unit),
        defaultAmount: from_candid_DefaultAmount_n19(_uploadFile, _downloadFile, value.defaultAmount),
        weeklyTarget: value.weeklyTarget
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthlyTargets: Array<_MonthlyTarget>;
    investmentDiaryEntries: Array<_InvestmentDiaryEntry>;
    habitRecords: Array<_HabitRecord>;
    diaryEntries: Array<[string, _DiaryEntry]>;
    investmentGoals: Array<_InvestmentGoal>;
    habits: Array<_Habit>;
    profile: [] | [_UserProfile];
}): {
    monthlyTargets: Array<MonthlyTarget>;
    investmentDiaryEntries: Array<InvestmentDiaryEntry>;
    habitRecords: Array<HabitRecord>;
    diaryEntries: Array<[string, DiaryEntry]>;
    investmentGoals: Array<InvestmentGoal>;
    habits: Array<Habit>;
    profile?: UserProfile;
} {
    return {
        monthlyTargets: value.monthlyTargets,
        investmentDiaryEntries: value.investmentDiaryEntries,
        habitRecords: from_candid_vec_n9(_uploadFile, _downloadFile, value.habitRecords),
        diaryEntries: value.diaryEntries,
        investmentGoals: value.investmentGoals,
        habits: from_candid_vec_n16(_uploadFile, _downloadFile, value.habits),
        profile: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: string;
} | {
    none: null;
} | {
    reps: null;
} | {
    time: null;
}): {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "reps";
    reps: null;
} | {
    __kind__: "time";
    time: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "none" in value ? {
        __kind__: "none",
        none: value.none
    } : "reps" in value ? {
        __kind__: "reps",
        reps: value.reps
    } : "time" in value ? {
        __kind__: "time",
        time: value.time
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Habit>): Array<Habit> {
    return value.map((x)=>from_candid_Habit_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HabitRecord>): Array<HabitRecord> {
    return value.map((x)=>from_candid_HabitRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_DefaultAmount_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DefaultAmount): _DefaultAmount {
    return to_candid_opt_n6(_uploadFile, _downloadFile, value);
}
function to_candid_HabitUnit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitUnit): _HabitUnit {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "reps";
    reps: null;
} | {
    __kind__: "time";
    time: null;
}): {
    custom: string;
} | {
    none: null;
} | {
    reps: null;
} | {
    time: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "none" ? {
        none: value.none
    } : value.__kind__ === "reps" ? {
        reps: value.reps
    } : value.__kind__ === "time" ? {
        time: value.time
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
